# Generated by Django 5.2.4 on 2025-07-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': ' کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9177381998, max_length=12, unique=True, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='آدرس ابمبل'),
        ),
    ]
