# Generated by Django 5.2.4 on 2025-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
