# Generated by Django 5.2.4 on 2025-07-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_information_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
