# Generated by Django 5.2.4 on 2025-08-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_job_informationjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
