# Generated by Django 5.2.4 on 2025-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sitestatistics_delete_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='total_visits',
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
