# Generated by Django 5.2.4 on 2025-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_sitestatistics_total_visits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestatistics',
            name='daily_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='last_week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitestatistics',
            name='weekly_visits',
            field=models.IntegerField(default=0),
        ),
    ]
